version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: odds_db
      POSTGRES_USER: odds_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  odds_service:
    build: .
    environment:
      DATABASE_URL: postgresql://odds_user:secure_password@postgres/odds_db
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.odds.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
