version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:2.14-pg15
    environment:
      POSTGRES_PASSWORD: cs2bet
    ports: ["5432:5432"]
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports: ["6379:6379"]
  nats:
    image: nats:2.10-alpine
    command: ["-js"]
    ports: ["4222:4222", "8222:8222"]
  api-gateway:
    build: ./services/api-gateway
    environment:
      - PORT=8000
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379/0
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    depends_on: [postgres, redis, nats]
  ingest-hltv:
    build: ./services/ingest-hltv
    environment:
      - SCRAPE_INTERVAL=10
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379/0
    depends_on: [nats, redis]
  ingest-odds:
    build: ./services/ingest-odds
    environment:
      - MATCH_ID=0
      - ODDS_INTERVAL=5
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379/0
      # bookmaker keys (optional)
      - ONEXBET_API_KEY=${ONEXBET_API_KEY:-}
      - BETWAY_API_KEY=${BETWAY_API_KEY:-}
      - PINNACLE_API_KEY=${PINNACLE_API_KEY:-}
    depends_on: [nats, redis]
  prediction:
    build: ./services/prediction
    environment:
      - REDIS_HOST=redis
    depends_on: [redis]
  feature-builder:
    build: ./services/feature-builder
    environment:
      - postgres_host=postgres
      - postgres_port=5432
      - postgres_db=cs2_analytics
      - postgres_user=postgres
      - postgres_password=cs2bet
      - redis_host=redis
      - redis_port=6379
      - redis_db=0
      - feature_ttl=3600
      - refresh_interval=300
    command: poetry run uvicorn feature_builder.main:app --host 0.0.0.0 --port 8003
    ports: ["8003:8003"]
    depends_on: [postgres, redis]
