version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:2.14-pg15
    environment:
      POSTGRES_PASSWORD: cs2bet
    ports: ["5432:5432"]
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports: ["6379:6379"]
  nats:
    image: nats:2.10-alpine
    command: ["-js"]
    ports: ["4222:4222", "8222:8222"]
  api-gateway:
    build: ./services/api-gateway
    environment:
      - PORT=8000
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    depends_on: [postgres, redis]
  ingest-hltv:
    build: ./services/ingest-hltv
    environment:
      - SCRAPE_INTERVAL=10
    depends_on: [nats]
  prediction:
    build: ./services/prediction
    environment:
      - REDIS_HOST=redis
    depends_on: [redis]
