global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scraper metrics
  - job_name: 'cs2_scraper'
    static_configs:
      - targets: ['hltv-scraper:8001']
    metrics_path: '/metrics'

  # PostgreSQL metrics  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alert rules
rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
