apiVersion: apps/v1
kind: Deployment
metadata:
  name: hltv-scraper
  labels:
    app: hltv-scraper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hltv-scraper
  template:
    metadata:
      labels:
        app: hltv-scraper
    spec:
      containers:
        - name: hltv-scraper
          image: your-registry/hltv-scraper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scraper-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: scraper-secrets
                  key: REDIS_URL
            - name: KAFKA_SERVERS
              valueFrom:
                secretKeyRef:
                  name: scraper-secrets
                  key: KAFKA_SERVERS
            - name: HEADLESS_MODE
              value: "true"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hltv-scraper
spec:
  selector:
    app: hltv-scraper
  ports:
    - name: http
      port: 80
      targetPort: 8001
